### ISSUE TITLE
Different OData Model Usage Error

### ISSUE THREAD

**Issue by eray01** [hasanciftci26/ui5-antares#2]
It's not working as expected when I tried to set different model name with setModel() method.

**Comment by hasanciftci26** [comment]
Hi @eray01, thanks for your feedback. setModelName() method was redundant and removed in #3 request. If you have a named OData model, you can specify your model name as the third parameter when creating an object from EntryCreateCL class. It's an optional parameter and if not specified, the OData model is assumed to be unnamed.
